all: sorting
	./sorting data/array_input/10_aleatorio_D1_a.txt

sorting: sorting.cpp algorithms/patiencesort.cpp algorithms/quicksort.cpp algorithms/mergesort.cpp algorithms/sort.cpp
	g++ sorting.cpp algorithms/patiencesort.cpp algorithms/quicksort.cpp algorithms/mergesort.cpp algorithms/sort.cpp -o sorting